import { AppProject, MarketplaceItem } from '@/types/aurabots';

export const STARTER_PROJECTS: AppProject[] = [
  {
    id: 'vault-fintech',
    name: 'AetherVault DeFi & Crypto Nexus',
    description: 'Real-time crypto portfolio tracker, staking yield calculator, asset exchange swap, live price charts, and multi-chain wallet management.',
    prompt: 'Build a high-performance crypto wallet and DeFi portfolio dashboard with live candlestick charts, token swap engine, staking yield calculator, transaction history, and dark titanium theme with neon cyan glow.',
    platform: 'hybrid',
    framework: 'react-web',
    theme: 'electric-cyan',
    version: '2.4.0',
    category: 'Fintech',
    tags: ['DeFi', 'Crypto', 'Web3', 'Trading', 'Wallet'],
    author: 'AuraBots Core Engine',
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 3600000,
    starred: true,
    activeFilePath: 'src/App.tsx',
    files: {}, // Will be populated by compiler synthesizer
    stats: {
      componentsCount: 8,
      linesOfCode: 540,
      astNodes: 120,
      bundleSizeBytes: 42300,
      compilationTimeMs: 380,
    }
  },
  {
    id: 'pulse-fit',
    name: 'PulseFit Pro & Bio-Telemetry',
    description: 'Native mobile & web fitness companion with HIIT interval timer, heart-rate zones, workout logging, calorie analytics, and GPS route visualization.',
    prompt: 'Create a sleek mobile-first fitness tracker with interactive interval timer, live biometric charts, workout logbook with set tracking, hydration counter, and calorie progress rings.',
    platform: 'mobile',
    framework: 'react-native',
    theme: 'neon-purple',
    version: '1.8.0',
    category: 'Health & Fitness',
    tags: ['Fitness', 'Mobile', 'HIIT', 'Telemetry', 'PWA'],
    author: 'NeoBio Lab',
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 7200000,
    starred: true,
    activeFilePath: 'src/App.tsx',
    files: {},
    stats: {
      componentsCount: 7,
      linesOfCode: 480,
      astNodes: 98,
      bundleSizeBytes: 38200,
      compilationTimeMs: 310,
    }
  },
  {
    id: 'quantum-iot',
    name: 'OmniGrid Smart Home & IoT Hub',
    description: 'Interactive smart home controller with live 3D room floor plan toggles, climate control thermostat, energy consumption graphs, and automated routines.',
    prompt: 'Synthesize a futuristic smart home dashboard with interactive room lighting controls, radial climate thermostat dial, live solar & power usage graphs, smart security locks, and quick scene automation switches.',
    platform: 'web',
    framework: 'react-web',
    theme: 'emerald-matrix',
    version: '3.1.0',
    category: 'IoT & Smart Home',
    tags: ['IoT', 'Smart Home', 'Dashboard', 'Sensors', 'Automation'],
    author: 'CyberGrid Systems',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 14400000,
    starred: false,
    activeFilePath: 'src/App.tsx',
    files: {},
    stats: {
      componentsCount: 9,
      linesOfCode: 610,
      astNodes: 145,
      bundleSizeBytes: 48900,
      compilationTimeMs: 420,
    }
  },
  {
    id: 'kanban-matrix',
    name: 'CyberSprint Agile Kanban & Workflow',
    description: 'High-velocity project management board with drag-drop cards, sprint burn-down telemetry, team allocation, and task automation triggers.',
    prompt: 'Build a modern agile project management app with interactive kanban columns (Backlog, In Progress, Code Review, Done), task creation modal with priority flags, sprint velocity stats, and dark theme.',
    platform: 'hybrid',
    framework: 'hybrid-expo',
    theme: 'cobalt-blue',
    version: '1.5.0',
    category: 'Productivity',
    tags: ['Kanban', 'Agile', 'Scrum', 'Productivity', 'Task Management'],
    author: 'SprintFlow Team',
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 1800000,
    starred: false,
    activeFilePath: 'src/App.tsx',
    files: {},
    stats: {
      componentsCount: 6,
      linesOfCode: 430,
      astNodes: 85,
      bundleSizeBytes: 34100,
      compilationTimeMs: 290,
    }
  },
  {
    id: 'apex-drop',
    name: 'Apex HypeDrop E-Commerce & Sneaker Vault',
    description: 'Limited edition sneaker & apparel release portal with live countdown timers, interactive 3D product showcase, shopping cart, and size selector.',
    prompt: 'Create a high-fashion streetwear e-commerce app with live drop countdown, interactive sneaker card gallery, size selector with stock indicators, sliding cart drawer, and instant checkout simulation.',
    platform: 'mobile',
    framework: 'react-native',
    theme: 'sunset-amber',
    version: '2.0.0',
    category: 'E-Commerce',
    tags: ['E-Commerce', 'Sneakers', 'Streetwear', 'Drop', 'Shopping'],
    author: 'Apex Drops Inc.',
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 25000000,
    starred: true,
    activeFilePath: 'src/App.tsx',
    files: {},
    stats: {
      componentsCount: 8,
      linesOfCode: 520,
      astNodes: 110,
      bundleSizeBytes: 41000,
      compilationTimeMs: 360,
    }
  },
  {
    id: 'omnichat-nexus',
    name: 'OmniChat Real-Time Audio & Voice Messenger',
    description: 'Next-gen encrypted communications hub with voice memo waveform recorder, thread channels, AI bot assistants, and media file attachments.',
    prompt: 'Build a modern encrypted messaging app with direct messages and server channels, interactive voice message recorder with audio waveforms, emoji reactions, message search, and typing indicators.',
    platform: 'hybrid',
    framework: 'react-web',
    theme: 'electric-cyan',
    version: '1.2.0',
    category: 'Social',
    tags: ['Chat', 'Messaging', 'Voice Notes', 'Channels', 'WebRTC'],
    author: 'Nexus Protocols',
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 43200000,
    starred: false,
    activeFilePath: 'src/App.tsx',
    files: {},
    stats: {
      componentsCount: 8,
      linesOfCode: 560,
      astNodes: 130,
      bundleSizeBytes: 44500,
      compilationTimeMs: 390,
    }
  }
];

export const INITIAL_MARKETPLACE: MarketplaceItem[] = STARTER_PROJECTS.map((proj, idx) => ({
  id: `mkt_${proj.id}`,
  name: proj.name,
  description: proj.description,
  author: proj.author,
  category: (proj.category as any) || 'Productivity',
  platform: proj.platform,
  downloads: 420 + idx * 315,
  priceUsd: 149 + idx * 50,
  stars: 4.8 - (idx % 3) * 0.1,
  userStarred: proj.starred,
  tags: proj.tags,
  project: proj,
  createdAt: '2026-08-20',
  verifiedBadge: true,
  status: 'active',
}));
